apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: anhabz3ya-go 
  janus-idp.io/tekton: anhabz3ya-go
  backstage.io/kubernetes-id: anhabz3ya-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: anhabz3ya-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml