apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: anhabz3ya-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: anhabz3ya-go 
  name: anhabz3ya-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: anhabz3ya-go 
